-- insertExceptPk の検証用
--   identity 列を自動採番として判定できることを確認する（REPO-014）
--   serial と違い column_default が空になるため、JDBC の IS_AUTOINCREMENT でのみ判別できる
create table identity_pk (
    pk                bigint generated by default as identity primary key,
    col_text          text,
    col_text_not_null text not null
);
